# Get mapping and store it in Mapping.csv
- name: create_mapping_csv
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create mapping.csv
      become: false
      shell: echo "Public_DNS, Tag Name, Tag Role, Internal IP" > mapping.csv

- name: ec2_metadata
  hosts: all_nodes
  gather_facts: no
  remote_user: ec2-user
  become: yes
  tasks:
    - include_vars: "{{ playbook_dir }}/mockfog_topology/vars/main.yml"

    - name: get_ec2_facts
      ec2_metadata_facts:
      register: ec2_facts

    - name: Retrieve all tags on an instance
      vars:
        ansible_python_interpreter: /usr/bin/python3
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
        state: list
      register: ec2_tags

    - name: Write to mapping.csv
      become: false
      local_action: shell echo "{{ ansible_ec2_public_hostname }}, {{ ec2_tags.tags.Name }}, {{ ec2_tags.tags.Role }}, {{ ec2_tags.tags.InternalIP }}" >> mapping.csv
      register: mapping
    - debug:
       msg: "{{ mapping }}"
