---
# Playbook to control the mockfog_application role

- name: Rollout ping application
  hosts: broker_nodes # based on defined role
  remote_user: ec2-user
  become: yes
  vars:
    container_name: generators
    image_name: jahandaniyal/mockfogload_generators
    expose: 8081
    ports: 8081:8080
  roles:
    - mockfog_application

- name: Rollout ping application
  hosts: client_nodes
  remote_user: ec2-user
  become: yes
  vars:
    container_name: application
    image_name: jahandaniyal/mockfogload_generators
    expose: 8081
    ports: 8081:8080
  roles:
    - mockfog_application
