---
- name: create agents dir
  file:
    path: "mockfog_agent/"
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user

- name: copy agent script
  copy:
    src: "{{ playbook_dir }}/mockfog_agent/mockfog_agent.py"
    dest: mockfog_agent/mockfog_agent.py
    owner: ec2-user
    group: ec2-user
    mode: '0642'

- name: install agent dependencies
  shell: "sudo pip3 install docker tcconfig"
  args:
    chdir: "mockfog_agent/"
  become_user: ec2-user

- name: start agent
  shell: "sudo nohup python3 mockfog_agent.py &"
  args:
    chdir: "mockfog_agent/"
  become_user: ec2-user